version: 2

updates:
  - schedule:
      interval: 'daily'
    reviewers:
      - 'trek'
    commit-message:
      prefix: '[framework-fixtures]'
    package-ecosystem: 'npm'
    directory: /scripts/framework-matrix/framework-fixtures/hydrogen-v2023
    allow:
      - dependency-name: "@remix-run"
      - dependency-name: "@shopify/cli"
      - dependency-name: "@shopify/cli-hydrogen"
      - dependency-name: "@shopify/hydrogen"
      - dependency-name: "@shopify/remix-oxygen"
    ignore:
      - dependency-name: "@remix-run"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "@shopify/cli"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "@shopify/cli-hydrogen"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "@shopify/hydrogen"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "@shopify/remix-oxygen"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    groups:
      core:
        patterns:
          - "@remix-run"
          - "@shopify/cli"
          - "@shopify/cli-hydrogen"
          - "@shopify/hydrogen"
          - "@shopify/remix-oxygen"
        update-types:
          - "minor"
  - schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
    reviewers:
      - 'trek'
    commit-message:
      prefix: '[framework-fixtures]'
    package-ecosystem: 'npm'
    directory: /scripts/framework-matrix/framework-fixtures/ionic-angular-v7
    allow:
      - dependency-name: "@angular*"
      - dependency-name: "@ionic*"
    ignore:
      - dependency-name: "@angular*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "@ionic*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    groups:
      core:
        patterns:
          - "@angular*"
          - "@ionic*"
        update-types:
          - "minor"
  - schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
    reviewers:
      - 'trek'
    commit-message:
      prefix: '[framework-fixtures]'
    package-ecosystem: 'npm'
    directory: /scripts/framework-matrix/framework-fixtures/ionic-react-v7
    allow:
      - dependency-name: "@ionic*"
      - dependency-name: "react*"
    groups:
      core:
        patterns:
          - "@ionic*"
          - "react*"
        update-types:
          - "minor"
  - schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
    reviewers:
      - 'trek'
    commit-message:
      prefix: '[framework-fixtures]'
    package-ecosystem: 'npm'
    directory: /scripts/framework-matrix/framework-fixtures/nuxt-v3
    allow:
      - dependency-name: "nuxt"
      - dependency-name: "vue"
      - dependency-name: "vue-router"
      - dependency-name: "@nuxt-devtools"
    groups:
      core:
        patterns:
          - "nuxt"
          - "vue"
          - "vue-router"
          - "@nuxt-devtools"
        update-types:
          - "minor"
  - schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
    reviewers:
      - 'trek'
    commit-message:
      prefix: '[framework-fixtures]'
    package-ecosystem: 'npm'
    directory: /scripts/framework-matrix/framework-fixtures/stencil-v4
    allow:
      - dependency-name: "@stencil/core"
    groups:
      core:
        patterns:
          - "@stencil/core"
        update-types:
          - "minor"
  - schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
    reviewers:
      - 'trek'
    commit-message:
      prefix: '[framework-fixtures]'
    package-ecosystem: 'npm'
    directory: /scripts/framework-matrix/framework-fixtures/vite-5
    allow:
      - dependency-name: "vite"
    groups:
      core:
        patterns:
          - "vite"
        update-types:
          - "minor"
  - schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
    reviewers:
      - 'trek'
    commit-message:
      prefix: '[framework-fixtures]'
    package-ecosystem: 'npm'
    directory: /scripts/framework-matrix/framework-fixtures/sveltekit-v2
    allow:
      - dependency-name: "svelte"
      - dependency-name: "vite"
      - dependency-name: "@svelte*"
    groups:
      core:
        patterns:
          - "svelte"
          - "vite"
          - "@svelte*"
        update-types:
          - "minor"
